expense_tracker/expense_tracker/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('expenses.urls'))
]

expense_tracker/expenses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.expense_list,name="expense_list"),
    path('add/',views.add_expense,name='add_expense'),
    path('delete/<int:expense_id>/',views.delete_expense,name='delete_expense'),
    path("signup/", views.signup, name="signup"),
     path("login/", views.loginView, name="login"),
     path("logout/", views.logoutView, name="logout"),
    
]

expense_tracker/expenses/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Expense(models.Model):
    CATEGORY_CHOICES = [
        ('Food', 'Food'),
        ('Travel', 'Travel'),
        ('Bills', 'Bills'),
        ('Others', 'Others'),
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=250)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    date = models.DateField(default=timezone.now, blank=True, null=True)  # ✅ manual ya default

    def __str__(self) -> str:
        return f"{self.description} - {self.amount}"

expense_tracker/expenses/forms.py
from django import forms
from .models import Expense
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['amount', 'description', 'category', 'date']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})  # ✅ sirf date picker
        }


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

expense_tracker/expenses/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Expense
from .forms import ExpenseForm,SignUpForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(redirect_field_name='next',login_url='login')
def expense_list(request):
    user = request.user
    expenses = Expense.objects.filter(user = user).order_by('-date')
    total = sum(e.amount for e in expenses)

    return render(request,'expenses/expense_list.html',{'expenses':expenses,'total':total})

@login_required(redirect_field_name='next',login_url='login')
def add_expense(request):
    user = request.user
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)  
            expense.user = request.user   # 👈 current user assign
            expense.save()
            return redirect('expense_list')
    else:
        form = ExpenseForm()

    return render(request, 'expenses/add_expense.html', {'form': form})

def delete_expense(request,expense_id):
    expense = get_object_or_404(Expense,id=expense_id)
    expense.delete()
    return redirect('expense_list')

def loginView(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_superuser or user.is_staff:
                    messages.error(request, "Admin users are not allowed to login here.")
                    return redirect("login")  # ya wahi page reload
                login(request,user)
                return redirect('add_expense')
            else:
                messages.error(request, "Invalid username or password")
            
    else:
        form = AuthenticationForm()
    return render(request,'expenses/login.html',{'form':form})


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful! Please log in.")
            return redirect("login")   # login page ka name url.py me "login" hona chahiye
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = SignUpForm()
    return render(request, "expenses/signup.html", {"form": form})

def logoutView(request):
    logout(request)
    return redirect('login')

expense_tracker/expenses/templates/expenses/add_expense.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block title %}
  Add Expense 
{% endblock %}

{% block content %}
  <div class="container mt-4" style="height: 80vh;">
    <h1 class="mb-4 text-center">Add Expense</h1>
    <form method="POST" class="p-4 border rounded shadow-sm bg-light">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_category" class="form-label">Category</label>
        {{ form.category|add_class:"form-select" }}
      </div>

      <div class="mb-3">
        <label for="id_amount" class="form-label">Amount (₹)</label>
        {{ form.amount|add_class:"form-control" }}
      </div>

      <div class="mb-3">
        <label for="id_date" class="form-label">Date</label>
        {{ form.date|add_class:"form-control" }}
      </div>

      <div class="mb-3">
        <label for="id_description" class="form-label">Description</label>
        {{ form.description|add_class:"form-control" }}
      </div>

      <button type="submit" class="btn btn-primary">Add</button>
      <a href="{% url 'expense_list' %}" class="btn btn-secondary">Back to list</a>
    </form>
  </div>
{% endblock %}

expense_tracker/expenses/templates/expenses/expense_list.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
  Expense List
{% endblock %}

{% block content %}
<div class="container" style="height: 80vh;">
   <h1 class="my-4 text-center">Expense List</h1>
  <table class="table table-bordered my-4 mb-0 text-center align-middle">
    <thead class="">
      <tr>
        <th>Category</th>
        <th>Amount (₹)</th>
        <th>Date</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for expense in expenses %}
        <tr>
          <td>{{ expense.category }}</td>
          <td>{{ expense.amount }}</td>
          <td>{{ expense.date|date:"d-m-Y" }}</td>
          <td>{{ expense.description }}</td>
          <td>
            <a href="{% url "delete_expense" expense.id %}" class="btn btn-danger btn-sm delete-btn" style="font-weight: bold; border-radius: 0.5rem;" onclick="handleDelete">Delete</a>
          </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No expenses yet</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="5" class="text">Total Expense : <b>₹{{ total }}</b></td>
        </tr>
    </tbody>
  </table>
  <p>No expenses recorded yet. <a href="{% url 'add_expense' %}">Add New Expense</a></p>
</div>
  <script src="{% static 'Javascripts/expense.js' %}"></script>
  {% endblock %}

expense_tracker/expenses/templates/expenses/login.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
  Expenses Track - Login Page
{% endblock %}

{% block content %}
  <div class="container" style="display: flex;justify-content: center;align-items: center;height: 80vh;">
    <form method="POST" style="width: 100%; max-width: 500px; background: #fff; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 0 10px rgba(0,0,0,0.1);">
      {% csrf_token %}
      <h2 class="text-center">Login</h2>
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ error }}
          <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      {% endfor %}
        {% for message in messages %}
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Username</label>
        <input type="text" class="form-control" id="exampleInputUsername1" aria-describedby="usernameHelp" name="username" {{ form.username.value|default_if_none:'' }} />
        {% for error in form.username.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" name="password" />
        {% for error in form.password.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1" />
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-outline-primary font-bold" style="width: 100%;font-weight: bolder;">Login</button>
      <p class="mt-4 text-center">
        Don't have an account? <a href="{% url 'signup' %}" class="link-info">Register here</a>
      </p>
    </form>
  </div>
{% endblock %}

expense_tracker/expenses/templates/expenses/signup.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
  Register - Expense Tracker
{% endblock %}

{% block content %}
  <div class="container" style="display: flex;justify-content: center;">
    <form method="POST" style="width: 100%; max-width: 500px; background: #fff; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 0 10px rgba(0,0,0,0.1);height: fit-content;">
      {% csrf_token %}
      <h3 class="text-center mb-4">Register</h3>

      {% if form.non_field_errors %}
        <div class="alert alert-danger">{{ form.non_field_errors }}</div>
      {% endif %}
      {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
      {% endfor %}
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" name="username" class="form-control" value="{{ form.username.value|default_if_none:'' }}" />
        {% for error in form.username.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>

      <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" name="email" class="form-control" value="{{ form.email.value|default_if_none:'' }}" />
        {% for error in form.email.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>

      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" name="password1" class="form-control" />
        {% for error in form.password1.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>

      <div class="mb-3">
        <label class="form-label">Confirm Password</label>
        <input type="password" name="password2" class="form-control" />
        {% for error in form.password2.errors %}
          <div class="text-danger small">* {{ error }}</div>
        {% endfor %}
      </div>

      <button type="submit" class="btn btn-success w-100">Sign Up</button>
      <p class="mt-3 text-center">
        Already have an account? <a href="{% url 'login' %}">Login here</a>
      </p>
    </form>
  </div>
{% endblock %}

expense_tracker/expenses/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>
      {% block title %}
        Expense Tracker
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous" />
  </head>
  <style>
    main {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      padding: 2rem;
    }
  </style>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark text-white" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="font-weight: bold;">Expense Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
          <ul class="navbar-nav">
            <li class="nav-item mx-2">
              <a class="nav-link active" href="{% url 'expense_list' %}">Expense</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link active" aria-current="page" href="{% url 'add_expense' %}">Add Expense</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link active" href="#">Summary</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item mx-2">
                <a class="nav-link active" href="#">Welcome, {{ request.user.username }}</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item mx-2">
                <a class="nav-link active" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link active" href="{% url 'signup' %}">Registration</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <div class="container-fluid bg-dark text-light" style="position:relative;bottom:0px">
      <p class="text-center mb-0 py-3">
        &copy; {% now 'Y' %} Expense Tracker. All rights reserved
      </p>
    </div>
    <script>
      // sabhi alerts ko 3 second baad hide karo
      setTimeout(function () {
        let alerts = document.querySelectorAll('.alert')
        alerts.forEach(function (alert) {
          // fade-out effect
          alert.classList.remove('show')
          alert.classList.add('fade')
          // phir DOM se hata do
          setTimeout(() => alert.remove(), 500)
        })
      }, 2000) // 3000ms = 3 second
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>